import { TanStackRouterVite } from '@tanstack/router-vite-plugin'
import react from '@vitejs/plugin-react-swc'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['/favicon.svg', '/apple-touch-icon.png'],
      injectRegister: 'auto',
      manifest: {
        name: 'ChefCam.',
        short_name: 'chefcam',
        description:
          'Just take a picture of your refrigerator and you can instantly search for your dinner recipe.',
        theme_color: '#00ac3d',
        icons: [
          {
            src: 'pwa_192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'pwa_512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'pwa_512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'pwa_512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
    TanStackRouterVite({
      generatedRouteTree: './src/lib/tanstack-router/route-tree.gen.ts',
      routesDirectory: 'src/routes',
      routeFileIgnorePrefix: '.',
      semicolons: false,
      quoteStyle: 'single',
      routeTreeFileHeader: ['// biome-ignore lint: this file is auto-generated by TanStack Router'],
      routeTreeFileFooter: [],
    }),
  ],
})
