// biome-ignore lint: this file is auto-generated by TanStack Router

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../../routes/__root'
import { Route as AppImport } from './../../routes/_app'
import { Route as IndexImport } from './../../routes/index'
import { Route as AppUploadImport } from './../../routes/_app/upload'
import { Route as AppRecipeImport } from './../../routes/_app/recipe'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppUploadRoute = AppUploadImport.update({
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)

const AppRecipeRoute = AppRecipeImport.update({
  path: '/recipe',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/recipe': {
      id: '/_app/recipe'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof AppRecipeImport
      parentRoute: typeof AppImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AppRoute: AppRoute.addChildren({ AppRecipeRoute, AppUploadRoute }),
})

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/recipe",
        "/_app/upload"
      ]
    },
    "/_app/recipe": {
      "filePath": "_app/recipe.tsx",
      "parent": "/_app"
    },
    "/_app/upload": {
      "filePath": "_app/upload.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
